x-kafka-deltalake-minio-template: &kafka-deltalake-minio-template
  image: kafka-deltalake-minio:latest
  build:
    context: .
    dockerfile: ./Dockerfile
  env_file:
   - .env
   - ./config/docker.env
  restart: always
  networks:
    - kafka-deltalake-minio


services:
  kafka-consumer:
    <<: *kafka-deltalake-minio-template
    environment:
      - SERVICE_NAME=kafka-consumer
    command: ["python", "src/kafka_deltalake_minio/jobs/consumers/delta_consumer.py"]
    deploy:
      mode: replicated
      replicas: 5

  mongo-syncer:
    <<: *kafka-deltalake-minio-template
    environment:
      - SERVICE_NAME=mongo-syncer
    command: ["python", "src/kafka_deltalake_minio/jobs/database/sync_mongo.py"]


networks:
  kafka-deltalake-minio:
    name: kafka-deltalake-minio
    driver: bridge
    external: true
      